package com.smartallies.incident.model;

public enum WorkflowState {
    INITIAL,
    AWAITING_CLASSIFICATION_CONFIRMATION,
    CLASSIFICATION_CONFIRMED,
    COLLECTING_DETAILS,
    AWAITING_REPORT_CONFIRMATION,
    AWAITING_HR_DECISION,
    HR_CONNECTED,
    REPORT_READY,
    COMPLETED,
    EMERGENCY_ACTIVE,
    ALERT_SENT
}
